// Generated by  Sound > Generate IDs  — do not edit by hand.
public static class SoundIds
{
    public static class BGM
    {
        public const string TMP_BGM001 = "TMP_BGM001";
        public const string TMP_BGM002 = "TMP_BGM002";
    }
    public static class Ambient
    {
    }
    public static class SFX
    {
        public const string TMP_SFX_BottleOnTable = "TMP_SFX_BottleOnTable";
        public const string TMP_SFX_BottleClink = "TMP_SFX_BottleClink";
        public const string TMP_SFX_Pouring = "TMP_SFX_Pouring";
        public const string TMP_Clock_TikTok = "TMP_Clock_TikTok";
        public const string Book_Close = "Book_Close";
        public const string Book_Open = "Book_Open";
        public const string Add_Ice = "Add_Ice";
        public const string FruiteCrack = "FruiteCrack";
    }
    public static class UiSFX
    {
    }
    public static class Voice
    {
    }
}
