using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>Sound ▸ Generate IDs — writes SoundIds.cs (const string per SoundData id) so code gets autocomplete + compile errors.</summary>
public static class SoundIdsGenerator
{
    private const string OutputPath = "Assets/[02]Script/Sound/SoundIds.cs";

    [MenuItem("Sound/Generate IDs")]
    private static void Generate()
    {
        var guids = AssetDatabase.FindAssets("t:SoundData");
        if (guids.Length == 0)
        {
            Debug.LogWarning("[SoundIds] ไม่พบ SoundData asset");
            return;
        }

        var data = AssetDatabase.LoadAssetAtPath<SoundData>(AssetDatabase.GUIDToAssetPath(guids[0]));

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by  Sound > Generate IDs  — do not edit by hand.");
        sb.AppendLine("public static class SoundIds");
        sb.AppendLine("{");
        AppendGroup(sb, "BGM", data.bgms);
        AppendGroup(sb, "Ambient", data.ambients);
        AppendGroup(sb, "SFX", data.effects);
        AppendGroup(sb, "UiSFX", data.uiSfx);
        AppendGroup(sb, "Voice", data.voices);
        sb.AppendLine("}");

        File.WriteAllText(OutputPath, sb.ToString());
        AssetDatabase.ImportAsset(OutputPath);
        Debug.Log($"[SoundIds] generated {OutputPath}");
    }

    private static void AppendGroup(StringBuilder sb, string group, List<SoundEntry> entries)
    {
        sb.AppendLine($"    public static class {group}");
        sb.AppendLine("    {");

        var seen = new HashSet<string>();
        foreach (var e in entries)
        {
            if (string.IsNullOrEmpty(e.id)) continue;

            string name = Sanitize(e.id);
            if (!seen.Add(name))
            {
                Debug.LogWarning($"[SoundIds] {group}: '{e.id}' ซ้ำกับ id อื่นหลังแปลงชื่อ ({name}) — ข้าม");
                continue;
            }
            sb.AppendLine($"        public const string {name} = \"{e.id.Replace("\\", "\\\\").Replace("\"", "\\\"")}\";");
        }

        sb.AppendLine("    }");
    }

    private static string Sanitize(string id)
    {
        var sb = new StringBuilder(id.Length + 1);
        foreach (char c in id) sb.Append(char.IsLetterOrDigit(c) && c < 128 || c == '_' ? c : '_');
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }
}
